version: "3.9"

services:

  api:
    build:
      context: .
      dockerfile: docker/Dockerfile.api

    ports:
      - "8000:8000"

    volumes:
      - ./models:/app/models

    runtime: nvidia

    environment:
      - NVIDIA_VISIBLE_DEVICES=all

    depends_on:
      - prometheus


  prometheus:
    image: prom/prometheus
    volumes:
      - ./monitoring/prometheus.yml:/etc/prometheus/prometheus.yml
    ports:
      - "9090:9090"


  grafana:
    image: grafana/grafana
    ports:
      - "3000:3000"